version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: mongo_agenda
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: node_agenda
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/agenda
    depends_on:
      - mongo
    volumes:
      - .:/app

volumes:
  mongo_data:
