version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/taskdb
    depends_on:
      - mongo
    networks:
      - task-network
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - task-network
volumes:
  mongo-data:
networks:
  task-network:
    driver: bridge